version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.11
    commands:
      - pip install aws-sam-cli
      - echo Installing dependencies...
      - cd Week10/Task2
      - mvn clean install
  pre_build:
    commands:
      - echo Running tests...
      - cd Week10/Task2
      - mvn test
  build:
    commands:
      - echo Building jar...
      - pwd
      - mvn package
      - echo Packaging SAM template...
      - pwd
      - sam package --template-file sam-template.yaml --s3-bucket $S3_BUCKET --output-template-file sam-template-packaged.yaml
artifacts:
  files:
    - Week10/Task2/lambda/sam-template-packaged.yaml
    - Week10/Task2/target/*.jar
  discard-paths: yes